#########################################################
# This file has been automatically generated by gem2tgz #
#########################################################
# -*- encoding: utf-8 -*-
# stub: minitest-global_expectations 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "minitest-global_expectations".freeze
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jeremy Evans".freeze]
  s.date = "2019-09-24"
  s.description = "minitest-global_expectations allows you to keep using simple code in your\nminitest specs, without having to wrap every single object you are calling\nan expectation method on with an underscore.\n".freeze
  s.email = "code@jeremyevans.net".freeze
  s.extra_rdoc_files = ["CHANGELOG".freeze, "MIT-LICENSE".freeze, "README.rdoc".freeze]
  s.files = ["CHANGELOG".freeze, "MIT-LICENSE".freeze, "README.rdoc".freeze, "Rakefile".freeze, "lib/minitest/global_expectations.rb".freeze, "lib/minitest/global_expectations/autorun.rb".freeze, "test/minitest_global_expectations_test.rb".freeze]
  s.homepage = "http://github.com/jeremyevans/minitest-global_expectations".freeze
  s.licenses = ["MIT".freeze]
  s.rdoc_options = ["--quiet".freeze, "--line-numbers".freeze, "--inline-source".freeze, "--title".freeze, "minitest-global_expectations: add expectation methods to all objects".freeze, "--main".freeze, "README.rdoc".freeze]
  s.rubygems_version = "3.1.2".freeze
  s.summary = "Support minitest expectation methods for all objects".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<minitest>.freeze, ["> 5"])
  else
    s.add_dependency(%q<minitest>.freeze, ["> 5"])
  end
end
